import { Poppins } from "next/font/google";
import "../sass/main.scss";
import { ThemeProvider } from "@/context/ThemeContext";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
// import PageSkinLeft from "@/components/ads/adsComponents/PageSkinLeft";
import { AdsContextProvider } from "@/context/AdsContext";
// import PageSkinRight from "@/components/ads/adsComponents/PageSkinRight";
import BaseWrapper from "@/components/BaseWrapper";
import { AuthenticationProvider } from "@/context/AuthenticationContext";
import { CategoriesProvider } from "@/context/CategoriesContext";
// import LogoNext from "@/components/ads/adsComponents/LogoNext";
// import MiniNavbar from '@/components/miniNavbar/MiniNavbar';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Herkes Duysun v1.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <AuthenticationProvider>
          <ThemeProvider>
            <CategoriesProvider>
              <AdsContextProvider>
                <Navbar />
                {/* <MiniNavbar /> */}
                {/* <LogoNext /> */}
                <BaseWrapper>{children}</BaseWrapper>
                <Footer />
              </AdsContextProvider>
            </CategoriesProvider>
          </ThemeProvider>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
